import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import * as p from "@clack/prompts";
import { stringify } from "yaml";
import { getErrorMessage, readEnv } from "./util.js";

interface PackageJson {
  scripts?: Record<string, string>;
  packageManager?: string;
}

interface Detected {
  pm: "npm" | "pnpm" | "yarn";
  test: string;
  build: string;
  lint: string;
  dev: string;
}

interface ProjectConfig {
  agent: "claude" | "codex";
  test: string;
  build: string;
  lint: string;
  dev: string;
  post_bootstrap: string[];
  limits: { max_turns: number; task_timeout: number };
  mcp_servers: Record<string, unknown>;
}

export function detectPackageManager(
  pkg: PackageJson,
  directory = process.cwd()
): "npm" | "pnpm" | "yarn" {
  if (pkg.packageManager?.startsWith("pnpm")) return "pnpm";
  if (pkg.packageManager?.startsWith("yarn")) return "yarn";
  if (existsSync(join(directory, "pnpm-lock.yaml"))) return "pnpm";
  if (existsSync(join(directory, "yarn.lock"))) return "yarn";
  return "npm";
}

export function detectProject(directory = process.cwd()): Detected {
  const packagePath = join(directory, "package.json");
  if (!existsSync(packagePath)) {
    throw new Error("No package.json found. Run openthrottle init from a Node.js project root.");
  }
  const pkg = JSON.parse(readFileSync(packagePath, "utf8")) as PackageJson;
  const scripts = pkg.scripts ?? {};
  const pm = detectPackageManager(pkg, directory);
  const run = (script: string) => (scripts[script] ? `${pm} run ${script}` : "");
  return {
    pm,
    test: run("test"),
    build: run("build"),
    lint: run("lint"),
    dev: scripts.dev ? `${pm} run dev -- --port 3000 --hostname 0.0.0.0` : "",
  };
}

async function promptConfig(detected: Detected): Promise<ProjectConfig> {
  const result = await p.group(
    {
      agent: () =>
        p.select({
          message: "Default agent",
          options: [
            { value: "claude", label: "Claude Code" },
            { value: "codex", label: "Codex CLI" },
          ],
          initialValue: "claude",
        }),
      test: () => p.text({ message: "Test command (blank to skip)", initialValue: detected.test }),
      build: () => p.text({ message: "Build command (blank to skip)", initialValue: detected.build }),
      lint: () => p.text({ message: "Lint command (blank to skip)", initialValue: detected.lint }),
      dev: () => p.text({ message: "Dev command (blank to skip)", initialValue: detected.dev }),
      post_bootstrap: () =>
        p.text({ message: "Post-bootstrap command", initialValue: `${detected.pm} install` }),
      max_turns: () => p.text({ message: "Max turns per agent run", initialValue: "200" }),
      task_timeout: () => p.text({ message: "Task timeout (seconds)", initialValue: "7200" }),
    },
    {
      onCancel: () => {
        p.cancel("Cancelled.");
        process.exit(0);
      },
    }
  );
  return {
    agent: result.agent as "claude" | "codex",
    test: result.test,
    build: result.build,
    lint: result.lint,
    dev: result.dev,
    post_bootstrap: result.post_bootstrap ? [result.post_bootstrap] : [],
    limits: {
      max_turns: Number(result.max_turns) || 200,
      task_timeout: Number(result.task_timeout) || 7200,
    },
    mcp_servers: {},
  };
}

export function writeProjectConfig(
  config: ProjectConfig,
  directory = process.cwd()
): void {
  const document: Record<string, unknown> = { ...config };
  for (const key of ["test", "build", "lint", "dev"] as const) {
    if (!config[key]) delete document[key];
  }
  const header = [
    "# .openthrottle.yml — project config for OpenThrottle",
    "# Generated by `openthrottle init`; commit this file.",
    "",
  ].join("\n");
  writeFileSync(join(directory, ".openthrottle.yml"), header + stringify(document));
}

async function verifySnapshot(snapshotName: string): Promise<void> {
  const apiKey = readEnv("DAYTONA_API_KEY");
  if (!apiKey) {
    p.log.warn(
      `DAYTONA_API_KEY is not set, so snapshot "${snapshotName}" could not be verified.\n` +
        `Create it from the OpenThrottle repo with:\n` +
        `  daytona snapshot create ${snapshotName} --dockerfile sandbox/Dockerfile --context .`
    );
    return;
  }
  const { Daytona } = await import("@daytona/sdk");
  const daytona = new Daytona({ apiKey });
  const spinner = p.spinner();
  spinner.start(`Verifying Daytona snapshot "${snapshotName}"`);
  try {
    const snapshot = await daytona.snapshot.get(snapshotName);
    spinner.stop(`Snapshot "${snapshot.name}" found (${snapshot.state}).`);
  } catch (error) {
    spinner.stop(`Snapshot "${snapshotName}" was not found.`);
    p.log.error(getErrorMessage(error));
    p.log.info(
      `Build it once from the OpenThrottle repository:\n` +
        `  daytona snapshot create ${snapshotName} --dockerfile sandbox/Dockerfile --context .`
    );
  }
}

const SUPERVISOR_ENV_VARS: Array<{ name: string; hint: string }> = [
  { name: "SUPERVISOR_URL", hint: "public HTTPS base URL" },
  { name: "OT_STATUS_TOKEN", hint: "random bearer token for CLI/status/stop/logs" },
  { name: "OT_INSTALL_SECRET", hint: "random bearer token for /oauth/install" },
  { name: "DATABASE_PATH", hint: "default: /data/openthrottle.db" },
  { name: "LINEAR_WEBHOOK_SECRET", hint: "Linear webhook signing secret" },
  { name: "LINEAR_CLIENT_ID", hint: "Linear OAuth agent app" },
  { name: "LINEAR_CLIENT_SECRET", hint: "Linear OAuth agent app" },
  { name: "LINEAR_MCP_API_KEY", hint: "restricted Linear API key for sandbox MCP" },
  { name: "GITHUB_WEBHOOK_SECRET", hint: "GitHub webhook signing secret" },
  { name: "GITHUB_TOKEN", hint: "fine-grained PAT: contents/PRs/checks" },
  { name: "GITHUB_REPO", hint: "default owner/name" },
  { name: "GITHUB_REPO_MAPPINGS", hint: "optional JSON map of Linear team id/key to repo" },
  { name: "DAYTONA_API_KEY", hint: "Daytona API key" },
  { name: "DAYTONA_SNAPSHOT", hint: "default: openthrottle" },
  { name: "CLAUDE_CODE_OAUTH_TOKEN", hint: "or ANTHROPIC_API_KEY" },
  { name: "ANTHROPIC_API_KEY", hint: "or CLAUDE_CODE_OAUTH_TOKEN" },
  { name: "CODEX_API_KEY", hint: "or CODEX_AUTH_JSON" },
  { name: "CODEX_AUTH_JSON", hint: "raw ~/.codex/auth.json, or CODEX_API_KEY" },
  { name: "BASE_BRANCH", hint: "default: main" },
  { name: "MAX_TURNS", hint: "default: 200" },
  { name: "TASK_TIMEOUT", hint: "seconds, default: 7200" },
  { name: "CALLBACK_GRACE_SECONDS", hint: "default: 120" },
  { name: "DEV_PORT", hint: "default: 3000" },
  { name: "SWEEP_MAX_AGE_DAYS", hint: "default: 14" },
  { name: "ORPHAN_GRACE_MINUTES", hint: "default: 5" },
  { name: "REVIEW_MAX_ROUNDS", hint: "default: 3" },
  { name: "ALLOW_LINEAR_MERGE", hint: "default: false" },
];

function printSecretsChecklist(): void {
  console.log("\nSupervisor secrets checklist:\n");
  for (const { name, hint } of SUPERVISOR_ENV_VARS) {
    console.log(`  fly secrets set ${name}="<value>"   # ${hint}`);
  }
}

export default async function init(): Promise<void> {
  p.intro("openthrottle init");
  let detected: Detected;
  try {
    detected = detectProject();
  } catch (error) {
    p.log.error(getErrorMessage(error));
    process.exit(1);
  }
  p.log.info(`Detected package manager: ${detected.pm}`);
  const config = await promptConfig(detected);
  const configPath = join(process.cwd(), ".openthrottle.yml");
  if (existsSync(configPath)) {
    const overwrite = await p.confirm({
      message: ".openthrottle.yml already exists. Overwrite?",
      initialValue: false,
    });
    if (p.isCancel(overwrite) || !overwrite) p.log.warn("Skipped .openthrottle.yml");
    else {
      writeProjectConfig(config);
      p.log.success("Wrote .openthrottle.yml");
    }
  } else {
    writeProjectConfig(config);
    p.log.success("Wrote .openthrottle.yml");
  }
  await verifySnapshot(readEnv("DAYTONA_SNAPSHOT") ?? "openthrottle");
  printSecretsChecklist();
  p.outro("Next: deploy supervisor/, install its Linear app, then ship a plan.");
}
